discord:
  token: ""
  destination_channel_id: 123
  receiver_channel_id: 123
  webhook_url: ""
  listening_users: [] # (list of user ids)

image:
  images_dir: "SavedImages"
  quality: 100
  type: jpeg

server:
  url:
    base: http://home.local:8000/observice
    logs_api_endpoint: /api/logs
    logs_endpoint: /logs

logger:
  show_logs_in_server: true

change_detector:
  refresh_rate: 60 # (in seconds)

image_receiver:
  refresh_rate: 5 # (in seconds)
